# Dataset Handling

#### Importing Libraries

In [1]:
import pandas as pd
import numpy as np

#### Import Datasets

In [8]:
claims_df = pd.read_csv("Synthetic Dataset.csv") # Claims Data
product_code = pd.read_csv("Product Mapping.csv") # Product Mapping Code
procedure_code = pd.read_csv("Procedure Mapping.csv",dtype='object') # Procedure Mapping Code
product_category =  pd.read_csv("Product Category.csv") # Product Category
claims_df['Transaction date'] = pd.to_datetime(claims_df['Transaction date'], format='%Y-%m-%d') # Converting date into datetime format

In [10]:
claims_df_real = pd.read_csv("Claims Data.csv") # Claims Data
claims_df_real['Transaction date'] = pd.to_datetime(claims_df_real['Transaction date'], format='%d-%m-%Y') # Converting date into datetime format

In [11]:
claims_df_real.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2830 entries, 0 to 2829
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Pat_ID            2830 non-null   object
 1   HCP_ID            2830 non-null   object
 2   Claim ID          2830 non-null   int64
 3   HCPCS_ code       2830 non-null   object
 4   Transaction date  2830 non-null   datetime64[ns]
 5   Diagnosis 1       2830 non-null   object
 6   Diagnosis 2       1750 non-null   object
 7   Diagnosis 3       1404 non-null   object
 8   Diagnosis 4       540 non-null    object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 199.1+ KB

In [12]:
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2471 entries, 0 to 2470
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Pat_ID            2471 non-null   object
 1   HCP_ID            2471 non-null   object
 2   Claim ID          2471 non-null   int64
 3   HCPCS_ code       2471 non-null   object
 4   Transaction date  2471 non-null   datetime64[ns]
 5   Diagnosis 1       2471 non-null   object
 6   Diagnosis 2       1952 non-null   object
 7   Diagnosis 3       1260 non-null   object
 8   Diagnosis 4       0 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 173.9+ KB

In [13]:
# Convert Diagnosis 4 column to object type
claims_df['Diagnosis 4'] = claims_df['Diagnosis 4'].astype(object)

In [14]:
claims_df = pd.merge(claims_df_real,claims_df,how='outer')

In [15]:
claims_df

,Pat_ID,HCP_ID,Claim ID,HCPCS_ code,Transaction date,Diagnosis 1,Diagnosis 2,Diagnosis 3,Diagnosis 4
0,PATIENT_001,HCP_17,2803,J1004,2022-01-12,C34.11,C78,S45901S,NaN
1,PATIENT_001,HCP_17,6213,J1001,2022-01-12,C34.11,C78,S45901S,NaN
2,PATIENT_001,HCP_17,6867,J1001,2022-02-11,C34.11,C78,N981,NaN
3,PATIENT_001,HCP_17,5629,J1001,2022-03-08,C34.11,C78,S55091A,NaN
4,PATIENT_001,HCP_17,8726,J1001,2022-04-12,C34.11,C78,S45901S,NaN
...,...,...,...,...,...,...,...,...,...
5296,PATIENT_425,HCP_77,2467,70552,2022-08-18,C34.2,C78.4,NaN,NaN
5297,PATIENT_425,HCP_77,2468,78815,2022-09-18,I10,C78.7,NaN,NaN
5298,PATIENT_425,HCP_77,2469,81235,2022-10-04,C34.1,C78.3,NaN,NaN
5299,PATIENT_425,HCP_77,2470,70551,2022-06-05,C34.1,C78.8,NaN,NaN
5300,PATIENT_425,HCP_77,2471,70450,2022-05-22,C34.8,75489,NaN,NaN

In [16]:
claims_df.to_csv('Merged Claims.csv',index=False)

In [17]:
claims_df['Pat_ID'].unique

<bound method Series.unique of 0       PATIENT_001
1       PATIENT_001
2       PATIENT_001
3       PATIENT_001
4       PATIENT_001
           ...
5296    PATIENT_425
5297    PATIENT_425
5298    PATIENT_425
5299    PATIENT_425
5300    PATIENT_425
Name: Pat_ID, Length: 5301, dtype: object>

#### Visualize the Data

In [18]:
claims_df.head()

,Pat_ID,HCP_ID,Claim ID,HCPCS_ code,Transaction date,Diagnosis 1,Diagnosis 2,Diagnosis 3,Diagnosis 4
0,PATIENT_001,HCP_17,2803,J1004,2022-01-12,C34.11,C78,S45901S,NaN
1,PATIENT_001,HCP_17,6213,J1001,2022-01-12,C34.11,C78,S45901S,NaN
2,PATIENT_001,HCP_17,6867,J1001,2022-02-11,C34.11,C78,N981,NaN
3,PATIENT_001,HCP_17,5629,J1001,2022-03-08,C34.11,C78,S55091A,NaN
4,PATIENT_001,HCP_17,8726,J1001,2022-04-12,C34.11,C78,S45901S,NaN

In [19]:
product_code.head()

  HCPCS_ code Product Name
0       J1001    Ticaprant
1       J1002   NOVmatinib
2       J1003    AZNertrib
3       J1004      BMSRizi
4       J2001   Pemetrexed

In [20]:
procedure_code.head()

  HCPCS_ code Procedure Name
0       81235      EGFR test
1       78815       PET scan
2       70450      Brain MRI
3       70460      Brain MRI
4       70470      Brain MRI

In [21]:
product_category.head()

  Product Name Product Category
0    Ticaprant    Market Basket
1   NOVmatinib    Market Basket
2    AZNertrib    Market Basket
3      BMSRizi    Market Basket
4   Pemetrexed     Chemotherapy

#### Map the Data (Product code, Procudere Codes and Product Category to Claims Data)

In [22]:
mapped_df = pd.merge(pd.merge(pd.merge(claims_df,product_code, how = 'left', on = 'HCPCS_ code'),procedure_code, how = 'left', on = 'HCPCS_ code'),product_category, how = 'left', on = 'Product Name')
mapped_df.head()

,Pat_ID,HCP_ID,Claim ID,HCPCS_ code,Transaction date,Diagnosis 1,Diagnosis 2,Diagnosis 3,Diagnosis 4,Product Name,Procedure Name,Product Category
0,PATIENT_001,HCP_17,2803,J1004,2022-01-12,C34.11,C78,S45901S,NaN,BMSRizi,NaN,Market Basket
1,PATIENT_001,HCP_17,6213,J1001,2022-01-12,C34.11,C78,S45901S,NaN,Ticaprant,NaN,Market Basket
2,PATIENT_001,HCP_17,6867,J1001,2022-02-11,C34.11,C78,N981,NaN,Ticaprant,NaN,Market Basket
3,PATIENT_001,HCP_17,5629,J1001,2022-03-08,C34.11,C78,S55091A,NaN,Ticaprant,NaN,Market Basket
4,PATIENT_001,HCP_17,8726,J1001,2022-04-12,C34.11,C78,S45901S,NaN,Ticaprant,NaN,Market Basket

# Patient Cohort Analysis

#### Full Claims Data (Assuming Cohort 1)

In [23]:
# Cohort 1: Full Claims Data
patient_cohort1_data = mapped_df
patient_cohort1_list = mapped_df['Pat_ID'].unique()
patient_cohort1_count = mapped_df['Pat_ID'].nunique()
print(patient_cohort1_list)
print(patient_cohort1_count)

['PATIENT_001' 'PATIENT_002' 'PATIENT_003' 'PATIENT_004' 'PATIENT_005'
 'PATIENT_006' 'PATIENT_007' 'PATIENT_008' 'PATIENT_009' 'PATIENT_010'
 'PATIENT_011' 'PATIENT_012' 'PATIENT_013' 'PATIENT_014' 'PATIENT_015'
 'PATIENT_016' 'PATIENT_017' 'PATIENT_018' 'PATIENT_019' 'PATIENT_020'
 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024' 'PATIENT_025'
 'PATIENT_026' 'PATIENT_027' 'PATIENT_028' 'PATIENT_029' 'PATIENT_030'
 'PATIENT_031' 'PATIENT_032' 'PATIENT_033' 'PATIENT_034' 'PATIENT_035'
 'PATIENT_036' 'PATIENT_037' 'PATIENT_038' 'PATIENT_039' 'PATIENT_040'
 'PATIENT_041' 'PATIENT_042' 'PATIENT_043' 'PATIENT_044' 'PATIENT_045'
 'PATIENT_046' 'PATIENT_047' 'PATIENT_048' 'PATIENT_049' 'PATIENT_050'
 'PATIENT_051' 'PATIENT_052' 'PATIENT_053' 'PATIENT_054' 'PATIENT_055'
 'PATIENT_056' 'PATIENT_057' 'PATIENT_058' 'PATIENT_059' 'PATIENT_060'
 'PATIENT_061' 'PATIENT_062' 'PATIENT_063' 'PATIENT_064' 'PATIENT_065'
 'PATIENT_066' 'PATIENT_067' 'PATIENT_068' 'PATIENT_069' 'PATIENT_070'
 'PATIENT_071' 'PATIENT_072' 'PATIENT_073' 'PATIENT_074' 'PATIENT_075'
 'PATIENT_076' 'PATIENT_077' 'PATIENT_078' 'PATIENT_079' 'PATIENT_080'
 'PATIENT_081' 'PATIENT_082' 'PATIENT_083' 'PATIENT_084' 'PATIENT_085'
 'PATIENT_086' 'PATIENT_087' 'PATIENT_088' 'PATIENT_089' 'PATIENT_090'
 'PATIENT_091' 'PATIENT_092' 'PATIENT_093' 'PATIENT_094' 'PATIENT_095'
 'PATIENT_096' 'PATIENT_097' 'PATIENT_098' 'PATIENT_099' 'PATIENT_100'
 'PATIENT_101' 'PATIENT_102' 'PATIENT_103' 'PATIENT_104' 'PATIENT_105'
 'PATIENT_106' 'PATIENT_107' 'PATIENT_108' 'PATIENT_109' 'PATIENT_110'
 'PATIENT_111' 'PATIENT_112' 'PATIENT_113' 'PATIENT_114' 'PATIENT_115'
 'PATIENT_116' 'PATIENT_117' 'PATIENT_118' 'PATIENT_119' 'PATIENT_120'
 'PATIENT_121' 'PATIENT_122' 'PATIENT_123' 'PATIENT_124' 'PATIENT_125'
 'PATIENT_126' 'PATIENT_127' 'PATIENT_128' 'PATIENT_129' 'PATIENT_130'
 'PATIENT_131' 'PATIENT_132' 'PATIENT_133' 'PATIENT_134' 'PATIENT_135'
 'PATIENT_136' 'PATIENT_137' 'PATIENT_138' 'PATIENT_139' 'PATIENT_140'
 'PATIENT_141' 'PATIENT_142' 'PATIENT_143' 'PATIENT_144' 'PATIENT_145'
 'PATIENT_146' 'PATIENT_147' 'PATIENT_148' 'PATIENT_149' 'PATIENT_150'
 'PATIENT_151' 'PATIENT_152' 'PATIENT_153' 'PATIENT_154' 'PATIENT_155'
 'PATIENT_156' 'PATIENT_157' 'PATIENT_158' 'PATIENT_159' 'PATIENT_160'
 'PATIENT_161' 'PATIENT_162' 'PATIENT_163' 'PATIENT_164' 'PATIENT_165'
 'PATIENT_166' 'PATIENT_167' 'PATIENT_168' 'PATIENT_169' 'PATIENT_170'
 'PATIENT_171' 'PATIENT_172' 'PATIENT_173' 'PATIENT_174' 'PATIENT_175'
 'PATIENT_176' 'PATIENT_177' 'PATIENT_178' 'PATIENT_179' 'PATIENT_180'
 'PATIENT_181' 'PATIENT_182' 'PATIENT_183' 'PATIENT_184' 'PATIENT_185'
 'PATIENT_186' 'PATIENT_187' 'PATIENT_188' 'PATIENT_189' 'PATIENT_190'
 'PATIENT_191' 'PATIENT_192' 'PATIENT_193' 'PATIENT_194' 'PATIENT_195'
 'PATIENT_196' 'PATIENT_197' 'PATIENT_198' 'PATIENT_199' 'PATIENT_200'
 'PATIENT_201' 'PATIENT_202' 'PATIENT_203' 'PATIENT_204' 'PATIENT_205'
 'PATIENT_206' 'PATIENT_207' 'PATIENT_208' 'PATIENT_209' 'PATIENT_210'
 'PATIENT_211' 'PATIENT_212' 'PATIENT_213' 'PATIENT_214' 'PATIENT_215'
 'PATIENT_216' 'PATIENT_217' 'PATIENT_218' 'PATIENT_219' 'PATIENT_220'
 'PATIENT_221' 'PATIENT_222' 'PATIENT_223' 'PATIENT_224' 'PATIENT_225'
 'PATIENT_226' 'PATIENT_227' 'PATIENT_228' 'PATIENT_229' 'PATIENT_230'
 'PATIENT_231' 'PATIENT_232' 'PATIENT_233' 'PATIENT_234' 'PATIENT_235'
 'PATIENT_236' 'PATIENT_237' 'PATIENT_238' 'PATIENT_239' 'PATIENT_240'
 'PATIENT_241' 'PATIENT_242' 'PATIENT_243' 'PATIENT_244' 'PATIENT_245'
 'PATIENT_246' 'PATIENT_247' 'PATIENT_248' 'PATIENT_249' 'PATIENT_250'
 'PATIENT_251' 'PATIENT_252' 'PATIENT_253' 'PATIENT_254' 'PATIENT_255'
 'PATIENT_256' 'PATIENT_257' 'PATIENT_258' 'PATIENT_259' 'PATIENT_260'
 'PATIENT_261' 'PATIENT_262' 'PATIENT_263' 'PATIENT_264' 'PATIENT_265'
 'PATIENT_266' 'PATIENT_267' 'PATIENT_268' 'PATIENT_269' 'PATIENT_270'
 'PATIENT_271' 'PATIENT_272' 'PATIENT_273' 'PATIENT_274' 'PATIENT_275'
 'PATIENT_276' 'PATIENT_277' 'PATIENT_278' 'PATIENT_279' 'PATIENT_280'
 'PATIENT_281' 'PATIENT_282' 'PATIENT_283' 'PATIENT_284' 'PATIENT_285'
 'PATIENT_286' 'PATIENT_287' 'PATIENT_288' 'PATIENT_289' 'PATIENT_290'
 'PATIENT_291' 'PATIENT_292' 'PATIENT_293' 'PATIENT_294' 'PATIENT_295'
 'PATIENT_296' 'PATIENT_297' 'PATIENT_298' 'PATIENT_299' 'PATIENT_300'
 'PATIENT_301' 'PATIENT_302' 'PATIENT_303' 'PATIENT_304' 'PATIENT_305'
 'PATIENT_306' 'PATIENT_307' 'PATIENT_308' 'PATIENT_309' 'PATIENT_310'
 'PATIENT_311' 'PATIENT_312' 'PATIENT_313' 'PATIENT_314' 'PATIENT_315'
 'PATIENT_316' 'PATIENT_317' 'PATIENT_318' 'PATIENT_319' 'PATIENT_320'
 'PATIENT_321' 'PATIENT_322' 'PATIENT_323' 'PATIENT_324' 'PATIENT_325'
 'PATIENT_326' 'PATIENT_327' 'PATIENT_328' 'PATIENT_329' 'PATIENT_330'
 'PATIENT_331' 'PATIENT_332' 'PATIENT_333' 'PATIENT_334' 'PATIENT_335'
 'PATIENT_336' 'PATIENT_337' 'PATIENT_338' 'PATIENT_339' 'PATIENT_340'
 'PATIENT_341' 'PATIENT_342' 'PATIENT_343' 'PATIENT_344' 'PATIENT_345'
 'PATIENT_346' 'PATIENT_347' 'PATIENT_348' 'PATIENT_349' 'PATIENT_350'
 'PATIENT_351' 'PATIENT_352' 'PATIENT_353' 'PATIENT_354' 'PATIENT_355'
 'PATIENT_356' 'PATIENT_357' 'PATIENT_358' 'PATIENT_359' 'PATIENT_360'
 'PATIENT_361' 'PATIENT_362' 'PATIENT_363' 'PATIENT_364' 'PATIENT_365'
 'PATIENT_366' 'PATIENT_367' 'PATIENT_368' 'PATIENT_369' 'PATIENT_370'
 'PATIENT_371' 'PATIENT_372' 'PATIENT_373' 'PATIENT_374' 'PATIENT_375'
 'PATIENT_376' 'PATIENT_377' 'PATIENT_378' 'PATIENT_379' 'PATIENT_380'
 'PATIENT_381' 'PATIENT_382' 'PATIENT_383' 'PATIENT_384' 'PATIENT_385'
 'PATIENT_386' 'PATIENT_387' 'PATIENT_388' 'PATIENT_389' 'PATIENT_390'
 'PATIENT_391' 'PATIENT_392' 'PATIENT_393' 'PATIENT_394' 'PATIENT_395'
 'PATIENT_396' 'PATIENT_397' 'PATIENT_398' 'PATIENT_399' 'PATIENT_400'
 'PATIENT_401' 'PATIENT_402' 'PATIENT_403' 'PATIENT_404' 'PATIENT_405'
 'PATIENT_406' 'PATIENT_407' 'PATIENT_408' 'PATIENT_409' 'PATIENT_410'
 'PATIENT_411' 'PATIENT_412' 'PATIENT_413' 'PATIENT_414' 'PATIENT_415'
 'PATIENT_416' 'PATIENT_417' 'PATIENT_418' 'PATIENT_419' 'PATIENT_420'
 'PATIENT_421' 'PATIENT_422' 'PATIENT_423' 'PATIENT_424' 'PATIENT_425']
425

#### NSCLC diagnosed Patients(Cohort 2)
- Diagnosis Code Starts with 'C34'
- Number of claim count must be greater than 2

In [24]:
# Ensure all Diagnosis columns are of string type
diagnosis_cols = ['Diagnosis 1', 'Diagnosis 2', 'Diagnosis 3', 'Diagnosis 4']
for col in diagnosis_cols:
    patient_cohort1_data[col] = patient_cohort1_data[col].astype(str)

# Cohort 2: NSCLC Patients
patient_cohort2_temp = patient_cohort1_data[
    (patient_cohort1_data['Diagnosis 1'].str.startswith('C34')) | 
    (patient_cohort1_data['Diagnosis 2'].str.startswith('C34')) |
    (patient_cohort1_data['Diagnosis 3'].str.startswith('C34')) | 
    (patient_cohort1_data['Diagnosis 4'].str.startswith('C34'))
].reset_index()

# NSCLC_diagnosis_claim_count
NSCLC_diagnosis_count = patient_cohort2_temp.groupby('Pat_ID').agg(
    NSCLC_claim_count=('Claim ID', 'count')
)
NSCLC_diagnosis_count.reset_index(inplace=True)

NSCLC_patient_list_two_claims = NSCLC_diagnosis_count[NSCLC_diagnosis_count['NSCLC_claim_count'] >= 2]['Pat_ID'].tolist()
patient_cohort2_data = patient_cohort1_data[patient_cohort1_data['Pat_ID'].isin(NSCLC_patient_list_two_claims)]
patient_cohort2_list = patient_cohort2_data['Pat_ID'].unique()
patient_cohort2_count = patient_cohort2_data['Pat_ID'].nunique()

print(patient_cohort2_list)
print(patient_cohort2_count)

['PATIENT_001' 'PATIENT_002' 'PATIENT_003' 'PATIENT_004' 'PATIENT_005'
 'PATIENT_006' 'PATIENT_007' 'PATIENT_008' 'PATIENT_009' 'PATIENT_010'
 'PATIENT_011' 'PATIENT_012' 'PATIENT_013' 'PATIENT_014' 'PATIENT_015'
 'PATIENT_016' 'PATIENT_017' 'PATIENT_018' 'PATIENT_019' 'PATIENT_020'
 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024' 'PATIENT_025'
 'PATIENT_026' 'PATIENT_027' 'PATIENT_028' 'PATIENT_029' 'PATIENT_030'
 'PATIENT_031' 'PATIENT_032' 'PATIENT_033' 'PATIENT_034' 'PATIENT_035'
 'PATIENT_036' 'PATIENT_037' 'PATIENT_038' 'PATIENT_039' 'PATIENT_040'
 'PATIENT_041' 'PATIENT_042' 'PATIENT_043' 'PATIENT_044' 'PATIENT_045'
 'PATIENT_046' 'PATIENT_047' 'PATIENT_048' 'PATIENT_049' 'PATIENT_050'
 'PATIENT_051' 'PATIENT_052' 'PATIENT_053' 'PATIENT_054' 'PATIENT_055'
 'PATIENT_056' 'PATIENT_057' 'PATIENT_058' 'PATIENT_059' 'PATIENT_060'
 'PATIENT_061' 'PATIENT_062' 'PATIENT_063' 'PATIENT_064' 'PATIENT_065'
 'PATIENT_066' 'PATIENT_067' 'PATIENT_068' 'PATIENT_069' 'PATIENT_070'
 'PATIENT_071' 'PATIENT_072' 'PATIENT_073' 'PATIENT_074' 'PATIENT_075'
 'PATIENT_076' 'PATIENT_077' 'PATIENT_078' 'PATIENT_079' 'PATIENT_080'
 'PATIENT_081' 'PATIENT_082' 'PATIENT_083' 'PATIENT_084' 'PATIENT_085'
 'PATIENT_086' 'PATIENT_087' 'PATIENT_088' 'PATIENT_089' 'PATIENT_090'
 'PATIENT_091' 'PATIENT_092' 'PATIENT_093' 'PATIENT_094' 'PATIENT_095'
 'PATIENT_096' 'PATIENT_097' 'PATIENT_098' 'PATIENT_099' 'PATIENT_100'
 'PATIENT_101' 'PATIENT_102' 'PATIENT_103' 'PATIENT_104' 'PATIENT_105'
 'PATIENT_106' 'PATIENT_107' 'PATIENT_108' 'PATIENT_109' 'PATIENT_110'
 'PATIENT_111' 'PATIENT_112' 'PATIENT_113' 'PATIENT_114' 'PATIENT_115'
 'PATIENT_116' 'PATIENT_117' 'PATIENT_118' 'PATIENT_119' 'PATIENT_120'
 'PATIENT_121' 'PATIENT_122' 'PATIENT_123' 'PATIENT_124' 'PATIENT_125'
 'PATIENT_126' 'PATIENT_127' 'PATIENT_128' 'PATIENT_129' 'PATIENT_130'
 'PATIENT_131' 'PATIENT_132' 'PATIENT_133' 'PATIENT_134' 'PATIENT_135'
 'PATIENT_137' 'PATIENT_138' 'PATIENT_139' 'PATIENT_140' 'PATIENT_141'
 'PATIENT_142' 'PATIENT_143' 'PATIENT_144' 'PATIENT_145' 'PATIENT_146'
 'PATIENT_147' 'PATIENT_148' 'PATIENT_149' 'PATIENT_150' 'PATIENT_151'
 'PATIENT_152' 'PATIENT_153' 'PATIENT_154' 'PATIENT_155' 'PATIENT_156'
 'PATIENT_157' 'PATIENT_158' 'PATIENT_159' 'PATIENT_160' 'PATIENT_161'
 'PATIENT_162' 'PATIENT_163' 'PATIENT_164' 'PATIENT_165' 'PATIENT_166'
 'PATIENT_167' 'PATIENT_168' 'PATIENT_169' 'PATIENT_170' 'PATIENT_171'
 'PATIENT_172' 'PATIENT_173' 'PATIENT_174' 'PATIENT_175' 'PATIENT_176'
 'PATIENT_177' 'PATIENT_178' 'PATIENT_179' 'PATIENT_180' 'PATIENT_181'
 'PATIENT_182' 'PATIENT_183' 'PATIENT_184' 'PATIENT_185' 'PATIENT_186'
 'PATIENT_187' 'PATIENT_188' 'PATIENT_189' 'PATIENT_190' 'PATIENT_191'
 'PATIENT_192' 'PATIENT_193' 'PATIENT_194' 'PATIENT_195' 'PATIENT_196'
 'PATIENT_197' 'PATIENT_198' 'PATIENT_199' 'PATIENT_200' 'PATIENT_201'
 'PATIENT_202' 'PATIENT_203' 'PATIENT_204' 'PATIENT_205' 'PATIENT_206'
 'PATIENT_207' 'PATIENT_208' 'PATIENT_209' 'PATIENT_210' 'PATIENT_211'
 'PATIENT_212' 'PATIENT_214' 'PATIENT_215' 'PATIENT_216' 'PATIENT_217'
 'PATIENT_218' 'PATIENT_219' 'PATIENT_220' 'PATIENT_221' 'PATIENT_222'
 'PATIENT_223' 'PATIENT_224' 'PATIENT_225' 'PATIENT_226' 'PATIENT_227'
 'PATIENT_228' 'PATIENT_229' 'PATIENT_230' 'PATIENT_231' 'PATIENT_232'
 'PATIENT_233' 'PATIENT_234' 'PATIENT_235' 'PATIENT_236' 'PATIENT_237'
 'PATIENT_238' 'PATIENT_239' 'PATIENT_240' 'PATIENT_241' 'PATIENT_242'
 'PATIENT_243' 'PATIENT_244' 'PATIENT_245' 'PATIENT_246' 'PATIENT_247'
 'PATIENT_248' 'PATIENT_249' 'PATIENT_250' 'PATIENT_251' 'PATIENT_252'
 'PATIENT_253' 'PATIENT_254' 'PATIENT_255' 'PATIENT_256' 'PATIENT_257'
 'PATIENT_258' 'PATIENT_259' 'PATIENT_260' 'PATIENT_261' 'PATIENT_262'
 'PATIENT_263' 'PATIENT_264' 'PATIENT_265' 'PATIENT_266' 'PATIENT_267'
 'PATIENT_268' 'PATIENT_269' 'PATIENT_270' 'PATIENT_271' 'PATIENT_272'
 'PATIENT_273' 'PATIENT_274' 'PATIENT_275' 'PATIENT_276' 'PATIENT_277'
 'PATIENT_278' 'PATIENT_279' 'PATIENT_280' 'PATIENT_281' 'PATIENT_282'
 'PATIENT_283' 'PATIENT_284' 'PATIENT_285' 'PATIENT_286' 'PATIENT_287'
 'PATIENT_288' 'PATIENT_289' 'PATIENT_290' 'PATIENT_291' 'PATIENT_292'
 'PATIENT_293' 'PATIENT_294' 'PATIENT_295' 'PATIENT_296' 'PATIENT_297'
 'PATIENT_298' 'PATIENT_299' 'PATIENT_300' 'PATIENT_301' 'PATIENT_302'
 'PATIENT_303' 'PATIENT_304' 'PATIENT_305' 'PATIENT_306' 'PATIENT_307'
 'PATIENT_308' 'PATIENT_309' 'PATIENT_310' 'PATIENT_311' 'PATIENT_312'
 'PATIENT_313' 'PATIENT_314' 'PATIENT_315' 'PATIENT_316' 'PATIENT_317'
 'PATIENT_318' 'PATIENT_319' 'PATIENT_320' 'PATIENT_321' 'PATIENT_322'
 'PATIENT_323' 'PATIENT_324' 'PATIENT_325' 'PATIENT_326' 'PATIENT_327'
 'PATIENT_328' 'PATIENT_329' 'PATIENT_330' 'PATIENT_331' 'PATIENT_332'
 'PATIENT_333' 'PATIENT_334' 'PATIENT_335' 'PATIENT_336' 'PATIENT_337'
 'PATIENT_338' 'PATIENT_339' 'PATIENT_340' 'PATIENT_341' 'PATIENT_342'
 'PATIENT_343' 'PATIENT_344' 'PATIENT_345' 'PATIENT_346' 'PATIENT_347'
 'PATIENT_348' 'PATIENT_349' 'PATIENT_350' 'PATIENT_351' 'PATIENT_352'
 'PATIENT_353' 'PATIENT_354' 'PATIENT_355' 'PATIENT_356' 'PATIENT_357'
 'PATIENT_358' 'PATIENT_359' 'PATIENT_360' 'PATIENT_361' 'PATIENT_362'
 'PATIENT_363' 'PATIENT_364' 'PATIENT_365' 'PATIENT_366' 'PATIENT_367'
 'PATIENT_368' 'PATIENT_369' 'PATIENT_370' 'PATIENT_371' 'PATIENT_372'
 'PATIENT_373' 'PATIENT_374' 'PATIENT_375' 'PATIENT_376' 'PATIENT_377'
 'PATIENT_378' 'PATIENT_379' 'PATIENT_380' 'PATIENT_381' 'PATIENT_382'
 'PATIENT_383' 'PATIENT_384' 'PATIENT_385' 'PATIENT_386' 'PATIENT_387'
 'PATIENT_388' 'PATIENT_389' 'PATIENT_390' 'PATIENT_391' 'PATIENT_392'
 'PATIENT_393' 'PATIENT_394' 'PATIENT_395' 'PATIENT_396' 'PATIENT_397'
 'PATIENT_398' 'PATIENT_399' 'PATIENT_400' 'PATIENT_401' 'PATIENT_402'
 'PATIENT_403' 'PATIENT_404' 'PATIENT_405' 'PATIENT_406' 'PATIENT_407'
 'PATIENT_408' 'PATIENT_409' 'PATIENT_410' 'PATIENT_411' 'PATIENT_412'
 'PATIENT_413' 'PATIENT_414' 'PATIENT_415' 'PATIENT_416' 'PATIENT_417'
 'PATIENT_418' 'PATIENT_419' 'PATIENT_420' 'PATIENT_421' 'PATIENT_422'
 'PATIENT_423' 'PATIENT_424' 'PATIENT_425']
423

In [25]:
'''# Cohort 2: NSCLC Patients
patient_cohort2_temp = patient_cohort1_data[(patient_cohort1_data['Diagnosis 1'].str.startswith('C34')) | (patient_cohort1_data['Diagnosis 2'].str.startswith('C34')) |
                                             (patient_cohort1_data['Diagnosis 3'].str.startswith('C34')) | (patient_cohort1_data['Diagnosis 4'].str.startswith('C34'))].reset_index()

# NSCLC_diagnosis_claim_count
NSCLC_diagnosis_count = patient_cohort2_temp.groupby('Pat_ID').agg(
    NSCLC_claim_count = ('Claim ID','count')
)
NSCLC_diagnosis_count.reset_index(inplace = True)

NSCLC_patient_list_two_claims = (NSCLC_diagnosis_count[NSCLC_diagnosis_count['NSCLC_claim_count'] >= 2]['Pat_ID']).tolist()
patient_cohort2_data = patient_cohort1_data[patient_cohort1_data['Pat_ID'].isin(NSCLC_patient_list_two_claims)]
patient_cohort2_list = patient_cohort2_data['Pat_ID'].unique()
patient_cohort2_count = patient_cohort2_data['Pat_ID'].nunique()
print(patient_cohort2_list)
print(patient_cohort2_count)'''

"# Cohort 2: NSCLC Patients\npatient_cohort2_temp = patient_cohort1_data[(patient_cohort1_data['Diagnosis 1'].str.startswith('C34')) | (patient_cohort1_data['Diagnosis 2'].str.startswith('C34')) |\n                                             (patient_cohort1_data['Diagnosis 3'].str.startswith('C34')) | (patient_cohort1_data['Diagnosis 4'].str.startswith('C34'))].reset_index()\n\n# NSCLC_diagnosis_claim_count\nNSCLC_diagnosis_count = patient_cohort2_temp.groupby('Pat_ID').agg(\n    NSCLC_claim_count = ('Claim ID','count')\n)\nNSCLC_diagnosis_count.reset_index(inplace = True)\n\nNSCLC_patient_list_two_claims = (NSCLC_diagnosis_count[NSCLC_diagnosis_count['NSCLC_claim_count'] >= 2]['Pat_ID']).tolist()\npatient_cohort2_data = patient_cohort1_data[patient_cohort1_data['Pat_ID'].isin(NSCLC_patient_list_two_claims)]\npatient_cohort2_list = patient_cohort2_data['Pat_ID'].unique()\npatient_cohort2_count = patient_cohort2_data['Pat_ID'].nunique()\nprint(patient_cohort2_list)\nprint(patient_cohort2_count)"

#### mNSCLC diagonosed Patients(Cohort 3)
- Diagnosis Code Starts with 'C78'
- Number of claim count must be greater than 2

In [26]:
# Cohort 3: mNSCLC Patients
patient_cohort3_temp = patient_cohort2_data[(patient_cohort2_data['Diagnosis 1'].str.startswith('C78')) | (patient_cohort2_data['Diagnosis 2'].str.startswith('C78')) |
                                             (patient_cohort2_data['Diagnosis 3'].str.startswith('C78')) | (patient_cohort2_data['Diagnosis 4'].str.startswith('C78'))].reset_index()


# mNSCLC_diagnosis_claim_count
mNSCLC_diagnosis_count = patient_cohort3_temp.groupby('Pat_ID').agg(
    mNSCLC_claim_count = ('Claim ID','count')
)
mNSCLC_diagnosis_count.reset_index(inplace = True)
mNSCLC_patient_list_two_claims = (mNSCLC_diagnosis_count[mNSCLC_diagnosis_count['mNSCLC_claim_count'] >= 2]['Pat_ID']).tolist()

patient_cohort3_data = patient_cohort2_data[patient_cohort2_data['Pat_ID'].isin(mNSCLC_patient_list_two_claims)]
patient_cohort3_list = patient_cohort3_data['Pat_ID'].unique()
patient_cohort3_count = patient_cohort3_data['Pat_ID'].nunique()
print(patient_cohort3_list)
print(patient_cohort3_count)

['PATIENT_001' 'PATIENT_002' 'PATIENT_003' 'PATIENT_004' 'PATIENT_005'
 'PATIENT_006' 'PATIENT_007' 'PATIENT_008' 'PATIENT_009' 'PATIENT_010'
 'PATIENT_011' 'PATIENT_012' 'PATIENT_013' 'PATIENT_014' 'PATIENT_015'
 'PATIENT_016' 'PATIENT_017' 'PATIENT_018' 'PATIENT_019' 'PATIENT_020'
 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024' 'PATIENT_025'
 'PATIENT_026' 'PATIENT_027' 'PATIENT_028' 'PATIENT_029' 'PATIENT_030'
 'PATIENT_031' 'PATIENT_032' 'PATIENT_033' 'PATIENT_034' 'PATIENT_035'
 'PATIENT_036' 'PATIENT_037' 'PATIENT_038' 'PATIENT_039' 'PATIENT_040'
 'PATIENT_041' 'PATIENT_042' 'PATIENT_043' 'PATIENT_044' 'PATIENT_045'
 'PATIENT_046' 'PATIENT_047' 'PATIENT_048' 'PATIENT_049' 'PATIENT_050'
 'PATIENT_051' 'PATIENT_052' 'PATIENT_053' 'PATIENT_054' 'PATIENT_055'
 'PATIENT_056' 'PATIENT_057' 'PATIENT_058' 'PATIENT_059' 'PATIENT_060'
 'PATIENT_061' 'PATIENT_062' 'PATIENT_063' 'PATIENT_064' 'PATIENT_065'
 'PATIENT_066' 'PATIENT_067' 'PATIENT_068' 'PATIENT_069' 'PATIENT_070'
 'PATIENT_071' 'PATIENT_072' 'PATIENT_073' 'PATIENT_074' 'PATIENT_075'
 'PATIENT_076' 'PATIENT_077' 'PATIENT_078' 'PATIENT_079' 'PATIENT_080'
 'PATIENT_081' 'PATIENT_082' 'PATIENT_083' 'PATIENT_084' 'PATIENT_085'
 'PATIENT_086' 'PATIENT_087' 'PATIENT_088' 'PATIENT_089' 'PATIENT_090'
 'PATIENT_116' 'PATIENT_117' 'PATIENT_118' 'PATIENT_119' 'PATIENT_120'
 'PATIENT_121' 'PATIENT_122' 'PATIENT_123' 'PATIENT_124' 'PATIENT_125'
 'PATIENT_126' 'PATIENT_127' 'PATIENT_128' 'PATIENT_129' 'PATIENT_130'
 'PATIENT_132' 'PATIENT_134' 'PATIENT_137' 'PATIENT_138' 'PATIENT_140'
 'PATIENT_141' 'PATIENT_143' 'PATIENT_144' 'PATIENT_145' 'PATIENT_146'
 'PATIENT_147' 'PATIENT_148' 'PATIENT_149' 'PATIENT_150' 'PATIENT_151'
 'PATIENT_152' 'PATIENT_153' 'PATIENT_154' 'PATIENT_155' 'PATIENT_156'
 'PATIENT_157' 'PATIENT_158' 'PATIENT_159' 'PATIENT_160' 'PATIENT_161'
 'PATIENT_162' 'PATIENT_163' 'PATIENT_164' 'PATIENT_165' 'PATIENT_166'
 'PATIENT_168' 'PATIENT_169' 'PATIENT_170' 'PATIENT_171' 'PATIENT_172'
 'PATIENT_173' 'PATIENT_174' 'PATIENT_176' 'PATIENT_177' 'PATIENT_180'
 'PATIENT_181' 'PATIENT_183' 'PATIENT_184' 'PATIENT_185' 'PATIENT_186'
 'PATIENT_187' 'PATIENT_188' 'PATIENT_189' 'PATIENT_190' 'PATIENT_191'
 'PATIENT_192' 'PATIENT_193' 'PATIENT_194' 'PATIENT_195' 'PATIENT_196'
 'PATIENT_197' 'PATIENT_198' 'PATIENT_201' 'PATIENT_202' 'PATIENT_204'
 'PATIENT_206' 'PATIENT_208' 'PATIENT_209' 'PATIENT_210' 'PATIENT_212'
 'PATIENT_214' 'PATIENT_216' 'PATIENT_217' 'PATIENT_218' 'PATIENT_219'
 'PATIENT_221' 'PATIENT_223' 'PATIENT_224' 'PATIENT_226' 'PATIENT_227'
 'PATIENT_228' 'PATIENT_229' 'PATIENT_230' 'PATIENT_232' 'PATIENT_233'
 'PATIENT_234' 'PATIENT_235' 'PATIENT_236' 'PATIENT_238' 'PATIENT_240'
 'PATIENT_241' 'PATIENT_242' 'PATIENT_243' 'PATIENT_244' 'PATIENT_245'
 'PATIENT_246' 'PATIENT_248' 'PATIENT_249' 'PATIENT_250' 'PATIENT_252'
 'PATIENT_253' 'PATIENT_255' 'PATIENT_256' 'PATIENT_257' 'PATIENT_259'
 'PATIENT_260' 'PATIENT_263' 'PATIENT_265' 'PATIENT_266' 'PATIENT_267'
 'PATIENT_268' 'PATIENT_269' 'PATIENT_270' 'PATIENT_271' 'PATIENT_273'
 'PATIENT_274' 'PATIENT_275' 'PATIENT_276' 'PATIENT_277' 'PATIENT_278'
 'PATIENT_279' 'PATIENT_280' 'PATIENT_281' 'PATIENT_283' 'PATIENT_286'
 'PATIENT_288' 'PATIENT_289' 'PATIENT_290' 'PATIENT_292' 'PATIENT_293'
 'PATIENT_294' 'PATIENT_295' 'PATIENT_296' 'PATIENT_297' 'PATIENT_298'
 'PATIENT_299' 'PATIENT_300' 'PATIENT_301' 'PATIENT_302' 'PATIENT_303'
 'PATIENT_304' 'PATIENT_305' 'PATIENT_307' 'PATIENT_308' 'PATIENT_309'
 'PATIENT_311' 'PATIENT_312' 'PATIENT_313' 'PATIENT_314' 'PATIENT_315'
 'PATIENT_316' 'PATIENT_317' 'PATIENT_318' 'PATIENT_319' 'PATIENT_320'
 'PATIENT_321' 'PATIENT_322' 'PATIENT_323' 'PATIENT_324' 'PATIENT_325'
 'PATIENT_328' 'PATIENT_329' 'PATIENT_330' 'PATIENT_331' 'PATIENT_332'
 'PATIENT_335' 'PATIENT_336' 'PATIENT_337' 'PATIENT_338' 'PATIENT_339'
 'PATIENT_340' 'PATIENT_341' 'PATIENT_342' 'PATIENT_343' 'PATIENT_344'
 'PATIENT_345' 'PATIENT_346' 'PATIENT_347' 'PATIENT_348' 'PATIENT_349'
 'PATIENT_350' 'PATIENT_351' 'PATIENT_353' 'PATIENT_354' 'PATIENT_355'
 'PATIENT_356' 'PATIENT_357' 'PATIENT_358' 'PATIENT_359' 'PATIENT_360'
 'PATIENT_362' 'PATIENT_363' 'PATIENT_364' 'PATIENT_365' 'PATIENT_366'
 'PATIENT_367' 'PATIENT_368' 'PATIENT_369' 'PATIENT_370' 'PATIENT_371'
 'PATIENT_372' 'PATIENT_373' 'PATIENT_374' 'PATIENT_375' 'PATIENT_377'
 'PATIENT_378' 'PATIENT_379' 'PATIENT_380' 'PATIENT_381' 'PATIENT_382'
 'PATIENT_383' 'PATIENT_384' 'PATIENT_385' 'PATIENT_386' 'PATIENT_387'
 'PATIENT_388' 'PATIENT_389' 'PATIENT_390' 'PATIENT_391' 'PATIENT_392'
 'PATIENT_393' 'PATIENT_394' 'PATIENT_395' 'PATIENT_396' 'PATIENT_397'
 'PATIENT_398' 'PATIENT_399' 'PATIENT_400' 'PATIENT_401' 'PATIENT_402'
 'PATIENT_403' 'PATIENT_404' 'PATIENT_405' 'PATIENT_406' 'PATIENT_407'
 'PATIENT_409' 'PATIENT_410' 'PATIENT_411' 'PATIENT_412' 'PATIENT_413'
 'PATIENT_414' 'PATIENT_416' 'PATIENT_419' 'PATIENT_420' 'PATIENT_421'
 'PATIENT_422' 'PATIENT_423' 'PATIENT_425']
348

In [27]:
## Reference data for further use: Limiting Patients only to metastatic pool that is mNSCLCpatients
mNSCLC_pat = pd.DataFrame({'mNSCLC_Patients':patient_cohort3_list})
mNSCLC_pat.to_csv('Synthetic mNSCLC Patients.csv',index = None)

#### mNSCLC Patient undergone EGFR Tests (Cohort 4)

In [28]:
# Cohort 4 : EGFR Patients
patient_cohort4_temp = patient_cohort3_data[patient_cohort3_data['Procedure Name'] == 'EGFR test'].reset_index()

patient_cohort4_data = patient_cohort3_data[patient_cohort3_data['Pat_ID'].isin(patient_cohort4_temp['Pat_ID'].unique())]
patient_cohort4_list = patient_cohort4_data['Pat_ID'].unique()
patient_cohort4_count = patient_cohort4_data['Pat_ID'].nunique()
print(patient_cohort4_list)
print(patient_cohort4_count)

['PATIENT_001' 'PATIENT_002' 'PATIENT_003' 'PATIENT_004' 'PATIENT_005'
 'PATIENT_006' 'PATIENT_007' 'PATIENT_008' 'PATIENT_009' 'PATIENT_010'
 'PATIENT_011' 'PATIENT_012' 'PATIENT_013' 'PATIENT_014' 'PATIENT_015'
 'PATIENT_016' 'PATIENT_017' 'PATIENT_018' 'PATIENT_019' 'PATIENT_020'
 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024' 'PATIENT_025'
 'PATIENT_026' 'PATIENT_027' 'PATIENT_028' 'PATIENT_029' 'PATIENT_030'
 'PATIENT_031' 'PATIENT_032' 'PATIENT_033' 'PATIENT_034' 'PATIENT_035'
 'PATIENT_036' 'PATIENT_037' 'PATIENT_038' 'PATIENT_039' 'PATIENT_040'
 'PATIENT_041' 'PATIENT_042' 'PATIENT_043' 'PATIENT_044' 'PATIENT_045'
 'PATIENT_046' 'PATIENT_047' 'PATIENT_048' 'PATIENT_049' 'PATIENT_050'
 'PATIENT_051' 'PATIENT_052' 'PATIENT_053' 'PATIENT_054' 'PATIENT_055'
 'PATIENT_056' 'PATIENT_057' 'PATIENT_058' 'PATIENT_059' 'PATIENT_060'
 'PATIENT_116' 'PATIENT_117' 'PATIENT_118' 'PATIENT_119' 'PATIENT_120'
 'PATIENT_121' 'PATIENT_122' 'PATIENT_123' 'PATIENT_124' 'PATIENT_125'
 'PATIENT_127' 'PATIENT_140' 'PATIENT_141' 'PATIENT_144' 'PATIENT_145'
 'PATIENT_146' 'PATIENT_147' 'PATIENT_149' 'PATIENT_150' 'PATIENT_153'
 'PATIENT_154' 'PATIENT_155' 'PATIENT_157' 'PATIENT_159' 'PATIENT_161'
 'PATIENT_162' 'PATIENT_163' 'PATIENT_170' 'PATIENT_171' 'PATIENT_172'
 'PATIENT_176' 'PATIENT_183' 'PATIENT_186' 'PATIENT_189' 'PATIENT_191'
 'PATIENT_192' 'PATIENT_201' 'PATIENT_202' 'PATIENT_206' 'PATIENT_216'
 'PATIENT_223' 'PATIENT_226' 'PATIENT_242' 'PATIENT_243' 'PATIENT_245'
 'PATIENT_249' 'PATIENT_252' 'PATIENT_255' 'PATIENT_256' 'PATIENT_257'
 'PATIENT_259' 'PATIENT_260' 'PATIENT_265' 'PATIENT_267' 'PATIENT_271'
 'PATIENT_275' 'PATIENT_276' 'PATIENT_278' 'PATIENT_280' 'PATIENT_286'
 'PATIENT_290' 'PATIENT_295' 'PATIENT_296' 'PATIENT_299' 'PATIENT_300'
 'PATIENT_302' 'PATIENT_304' 'PATIENT_305' 'PATIENT_312' 'PATIENT_313'
 'PATIENT_314' 'PATIENT_315' 'PATIENT_317' 'PATIENT_318' 'PATIENT_320'
 'PATIENT_321' 'PATIENT_322' 'PATIENT_323' 'PATIENT_324' 'PATIENT_325'
 'PATIENT_329' 'PATIENT_339' 'PATIENT_341' 'PATIENT_342' 'PATIENT_343'
 'PATIENT_345' 'PATIENT_347' 'PATIENT_350' 'PATIENT_356' 'PATIENT_359'
 'PATIENT_360' 'PATIENT_363' 'PATIENT_364' 'PATIENT_368' 'PATIENT_369'
 'PATIENT_370' 'PATIENT_379' 'PATIENT_380' 'PATIENT_381' 'PATIENT_382'
 'PATIENT_383' 'PATIENT_384' 'PATIENT_386' 'PATIENT_387' 'PATIENT_389'
 'PATIENT_392' 'PATIENT_393' 'PATIENT_394' 'PATIENT_395' 'PATIENT_397'
 'PATIENT_398' 'PATIENT_400' 'PATIENT_402' 'PATIENT_406' 'PATIENT_407'
 'PATIENT_411' 'PATIENT_412' 'PATIENT_413' 'PATIENT_416' 'PATIENT_425']
180

#### mNSCLC egfr patients who have taken Market products â€‹(Cohort 5)

In [29]:
# Cohort 5 : Targetted Therapy Product Patients
patient_cohort5_temp = patient_cohort4_data[patient_cohort4_data['Product Category'] == 'Market Basket'].reset_index()

patient_cohort5_data = patient_cohort4_data[patient_cohort4_data['Pat_ID'].isin(patient_cohort5_temp['Pat_ID'].unique())]
patient_cohort5_list = patient_cohort5_data['Pat_ID'].unique()
patient_cohort5_count = patient_cohort5_data['Pat_ID'].nunique()
print(patient_cohort5_list)
print(patient_cohort5_count)

['PATIENT_001' 'PATIENT_002' 'PATIENT_003' 'PATIENT_004' 'PATIENT_005'
 'PATIENT_006' 'PATIENT_007' 'PATIENT_008' 'PATIENT_009' 'PATIENT_010'
 'PATIENT_011' 'PATIENT_012' 'PATIENT_013' 'PATIENT_014' 'PATIENT_015'
 'PATIENT_016' 'PATIENT_017' 'PATIENT_018' 'PATIENT_019' 'PATIENT_020'
 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024' 'PATIENT_025'
 'PATIENT_026' 'PATIENT_027' 'PATIENT_028' 'PATIENT_029' 'PATIENT_030'
 'PATIENT_031' 'PATIENT_032' 'PATIENT_033' 'PATIENT_034' 'PATIENT_035'
 'PATIENT_036' 'PATIENT_037' 'PATIENT_038' 'PATIENT_039' 'PATIENT_040'
 'PATIENT_041' 'PATIENT_042' 'PATIENT_116' 'PATIENT_117' 'PATIENT_118'
 'PATIENT_119' 'PATIENT_120' 'PATIENT_121' 'PATIENT_122' 'PATIENT_123'
 'PATIENT_124' 'PATIENT_125' 'PATIENT_127' 'PATIENT_140' 'PATIENT_141'
 'PATIENT_144' 'PATIENT_145' 'PATIENT_146' 'PATIENT_147' 'PATIENT_149'
 'PATIENT_150' 'PATIENT_153' 'PATIENT_154' 'PATIENT_155' 'PATIENT_157'
 'PATIENT_159' 'PATIENT_161' 'PATIENT_162' 'PATIENT_163' 'PATIENT_170'
 'PATIENT_171' 'PATIENT_172' 'PATIENT_189' 'PATIENT_191' 'PATIENT_192'
 'PATIENT_201' 'PATIENT_202' 'PATIENT_206' 'PATIENT_216' 'PATIENT_223'
 'PATIENT_243' 'PATIENT_245' 'PATIENT_249' 'PATIENT_252' 'PATIENT_256'
 'PATIENT_257' 'PATIENT_259' 'PATIENT_260' 'PATIENT_265' 'PATIENT_267'
 'PATIENT_271' 'PATIENT_275' 'PATIENT_276' 'PATIENT_278' 'PATIENT_280'
 'PATIENT_286' 'PATIENT_290' 'PATIENT_295' 'PATIENT_296' 'PATIENT_299'
 'PATIENT_302' 'PATIENT_304' 'PATIENT_305' 'PATIENT_312' 'PATIENT_313'
 'PATIENT_314' 'PATIENT_315' 'PATIENT_317' 'PATIENT_318' 'PATIENT_320'
 'PATIENT_321' 'PATIENT_324' 'PATIENT_325' 'PATIENT_329' 'PATIENT_339'
 'PATIENT_342' 'PATIENT_343' 'PATIENT_345' 'PATIENT_347' 'PATIENT_350'
 'PATIENT_356' 'PATIENT_359' 'PATIENT_360' 'PATIENT_363' 'PATIENT_364'
 'PATIENT_368' 'PATIENT_369' 'PATIENT_370' 'PATIENT_379' 'PATIENT_380'
 'PATIENT_382' 'PATIENT_383' 'PATIENT_384' 'PATIENT_386' 'PATIENT_387'
 'PATIENT_389' 'PATIENT_392' 'PATIENT_393' 'PATIENT_394' 'PATIENT_395'
 'PATIENT_397' 'PATIENT_398' 'PATIENT_400' 'PATIENT_402' 'PATIENT_406'
 'PATIENT_407' 'PATIENT_411' 'PATIENT_412' 'PATIENT_413' 'PATIENT_416']
150

#### mNSCLC egfr patients who have taken Ticaprantâ€‹ (Cohort 6)

In [30]:
# Cohort 6 : Ticaprant Patients
patient_cohort6_temp = patient_cohort5_data[patient_cohort5_data['Product Name'] == 'Ticaprant'].reset_index()

patient_cohort6_data = patient_cohort5_data[patient_cohort5_data['Pat_ID'].isin(patient_cohort6_temp['Pat_ID'].unique())]
patient_cohort6_list = patient_cohort6_data['Pat_ID'].unique()
patient_cohort6_count = patient_cohort6_data['Pat_ID'].nunique()
print(patient_cohort6_list)
print(patient_cohort6_count)

['PATIENT_001' 'PATIENT_003' 'PATIENT_006' 'PATIENT_008' 'PATIENT_009'
 'PATIENT_010' 'PATIENT_012' 'PATIENT_014' 'PATIENT_017' 'PATIENT_019'
 'PATIENT_020' 'PATIENT_021' 'PATIENT_022' 'PATIENT_023' 'PATIENT_024'
 'PATIENT_028' 'PATIENT_029' 'PATIENT_030' 'PATIENT_031' 'PATIENT_032'
 'PATIENT_033' 'PATIENT_034' 'PATIENT_035' 'PATIENT_036' 'PATIENT_037'
 'PATIENT_038' 'PATIENT_039' 'PATIENT_040' 'PATIENT_041' 'PATIENT_042'
 'PATIENT_127' 'PATIENT_140' 'PATIENT_145' 'PATIENT_150' 'PATIENT_153'
 'PATIENT_155' 'PATIENT_159' 'PATIENT_172' 'PATIENT_191' 'PATIENT_192'
 'PATIENT_201' 'PATIENT_243' 'PATIENT_245' 'PATIENT_252' 'PATIENT_257'
 'PATIENT_265' 'PATIENT_267' 'PATIENT_275' 'PATIENT_278' 'PATIENT_296'
 'PATIENT_299' 'PATIENT_304' 'PATIENT_312' 'PATIENT_313' 'PATIENT_314'
 'PATIENT_318' 'PATIENT_320' 'PATIENT_324' 'PATIENT_329' 'PATIENT_339'
 'PATIENT_345' 'PATIENT_350' 'PATIENT_356' 'PATIENT_359' 'PATIENT_363'
 'PATIENT_370' 'PATIENT_380' 'PATIENT_382' 'PATIENT_392' 'PATIENT_393'
 'PATIENT_398' 'PATIENT_416']
72

#### Dates For Analysis
- First NSCLC diagnosis date
- First mNSCLC diagnosis date
- First EGFR date
- Last EGFR date

In [31]:
# Define a function to convert dates to mmddyyyy format, handling NaT values
def convert_to_mmddyyyy(date):
    if pd.notnull(date):  # Check if the date is not NaT
        return date.strftime('%Y%m%d')
    else:
        return None  # Return None or any placeholder you prefer for NaT

In [32]:
# NSCLC Patient (Refer to Patient Cohort 2)

NSCLC_date = patient_cohort2_temp.groupby('Pat_ID').agg(
    first_NSCLC_diagnosis_date = ('Transaction date','min')
)

# mNSCLC Patient (Refer to Patient Cohort 3)
mNSCLC_date = patient_cohort3_temp.groupby('Pat_ID').agg(
    first_mNSCLC_diagnosis_date = ('Transaction date','min')
)

# EGFR Patients (Refer to Patient Cohort 4)
egfr_dates = patient_cohort4_temp.groupby('Pat_ID').agg(
    first_egfr_date = ('Transaction date','min'),
    last_egfr_date = ('Transaction date','max')
)

# Apply the function to the 'date' column
NSCLC_date['first_NSCLC_diagnosis_date'] = NSCLC_date['first_NSCLC_diagnosis_date'].apply(convert_to_mmddyyyy)
mNSCLC_date['first_mNSCLC_diagnosis_date'] = mNSCLC_date['first_mNSCLC_diagnosis_date'].apply(convert_to_mmddyyyy)
egfr_dates['first_egfr_date'] = egfr_dates['first_egfr_date'].apply(convert_to_mmddyyyy)
egfr_dates['last_egfr_date'] = egfr_dates['last_egfr_date'].apply(convert_to_mmddyyyy)

# Create a temporary dataframe to collate all the dates
temp = NSCLC_date.merge(mNSCLC_date,on='Pat_ID', how = 'left').merge(egfr_dates,on='Pat_ID', how = 'left')

#### Patients undergone chemo

In [33]:
# Chemo Patients
# J2001 and J2002
chemo_filter = mapped_df[mapped_df['HCPCS_ code'].isin(['J2001','J2002'])]
unique_chemo_patient = chemo_filter['Pat_ID'].unique()

print(unique_chemo_patient)
print(len(unique_chemo_patient))

['PATIENT_043' 'PATIENT_044' 'PATIENT_045' 'PATIENT_046' 'PATIENT_047'
 'PATIENT_048' 'PATIENT_049' 'PATIENT_050' 'PATIENT_051' 'PATIENT_052'
 'PATIENT_053' 'PATIENT_054' 'PATIENT_055' 'PATIENT_056' 'PATIENT_057'
 'PATIENT_058' 'PATIENT_059' 'PATIENT_060' 'PATIENT_061' 'PATIENT_062'
 'PATIENT_063' 'PATIENT_064' 'PATIENT_065' 'PATIENT_066' 'PATIENT_067'
 'PATIENT_068' 'PATIENT_069' 'PATIENT_070' 'PATIENT_071' 'PATIENT_072'
 'PATIENT_073' 'PATIENT_074' 'PATIENT_075' 'PATIENT_076' 'PATIENT_077'
 'PATIENT_078' 'PATIENT_079' 'PATIENT_080' 'PATIENT_081' 'PATIENT_082'
 'PATIENT_083' 'PATIENT_084' 'PATIENT_085' 'PATIENT_086' 'PATIENT_087'
 'PATIENT_088' 'PATIENT_089' 'PATIENT_090' 'PATIENT_126' 'PATIENT_127'
 'PATIENT_128' 'PATIENT_129' 'PATIENT_130' 'PATIENT_134' 'PATIENT_136'
 'PATIENT_140' 'PATIENT_141' 'PATIENT_143' 'PATIENT_144' 'PATIENT_145'
 'PATIENT_146' 'PATIENT_148' 'PATIENT_150' 'PATIENT_151' 'PATIENT_152'
 'PATIENT_155' 'PATIENT_156' 'PATIENT_157' 'PATIENT_158' 'PATIENT_159'
 'PATIENT_160' 'PATIENT_161' 'PATIENT_165' 'PATIENT_166' 'PATIENT_167'
 'PATIENT_168' 'PATIENT_169' 'PATIENT_170' 'PATIENT_171' 'PATIENT_172'
 'PATIENT_174' 'PATIENT_176' 'PATIENT_179' 'PATIENT_180' 'PATIENT_181'
 'PATIENT_184' 'PATIENT_185' 'PATIENT_186' 'PATIENT_187' 'PATIENT_188'
 'PATIENT_189' 'PATIENT_190' 'PATIENT_191' 'PATIENT_192' 'PATIENT_193'
 'PATIENT_194' 'PATIENT_195' 'PATIENT_196' 'PATIENT_197' 'PATIENT_198'
 'PATIENT_200' 'PATIENT_201' 'PATIENT_202' 'PATIENT_205' 'PATIENT_206'
 'PATIENT_208' 'PATIENT_209' 'PATIENT_211' 'PATIENT_213' 'PATIENT_214'
 'PATIENT_216' 'PATIENT_217' 'PATIENT_218' 'PATIENT_220' 'PATIENT_221'
 'PATIENT_229' 'PATIENT_230' 'PATIENT_231' 'PATIENT_232' 'PATIENT_233'
 'PATIENT_235' 'PATIENT_236' 'PATIENT_238' 'PATIENT_240' 'PATIENT_242'
 'PATIENT_243' 'PATIENT_244' 'PATIENT_245' 'PATIENT_247' 'PATIENT_248'
 'PATIENT_249' 'PATIENT_250' 'PATIENT_251' 'PATIENT_252' 'PATIENT_253'
 'PATIENT_254' 'PATIENT_255' 'PATIENT_257' 'PATIENT_260' 'PATIENT_261'
 'PATIENT_262' 'PATIENT_263' 'PATIENT_267' 'PATIENT_268' 'PATIENT_271'
 'PATIENT_272' 'PATIENT_275' 'PATIENT_276' 'PATIENT_277' 'PATIENT_278'
 'PATIENT_279' 'PATIENT_281' 'PATIENT_283' 'PATIENT_285' 'PATIENT_286'
 'PATIENT_287' 'PATIENT_292' 'PATIENT_293' 'PATIENT_294' 'PATIENT_295'
 'PATIENT_296' 'PATIENT_297' 'PATIENT_300' 'PATIENT_302' 'PATIENT_305'
 'PATIENT_307' 'PATIENT_308' 'PATIENT_309' 'PATIENT_312' 'PATIENT_313'
 'PATIENT_314' 'PATIENT_317' 'PATIENT_318' 'PATIENT_319' 'PATIENT_320'
 'PATIENT_324' 'PATIENT_326' 'PATIENT_327' 'PATIENT_329' 'PATIENT_331'
 'PATIENT_332' 'PATIENT_335' 'PATIENT_336' 'PATIENT_338' 'PATIENT_339'
 'PATIENT_340' 'PATIENT_341' 'PATIENT_342' 'PATIENT_344' 'PATIENT_346'
 'PATIENT_347' 'PATIENT_349' 'PATIENT_350' 'PATIENT_354' 'PATIENT_356'
 'PATIENT_357' 'PATIENT_358' 'PATIENT_359' 'PATIENT_363' 'PATIENT_364'
 'PATIENT_365' 'PATIENT_367' 'PATIENT_369' 'PATIENT_370' 'PATIENT_373'
 'PATIENT_374' 'PATIENT_375' 'PATIENT_377' 'PATIENT_378' 'PATIENT_379'
 'PATIENT_380' 'PATIENT_381' 'PATIENT_382' 'PATIENT_383' 'PATIENT_385'
 'PATIENT_386' 'PATIENT_387' 'PATIENT_388' 'PATIENT_389' 'PATIENT_391'
 'PATIENT_392' 'PATIENT_394' 'PATIENT_395' 'PATIENT_396' 'PATIENT_397'
 'PATIENT_398' 'PATIENT_400' 'PATIENT_403' 'PATIENT_406' 'PATIENT_411'
 'PATIENT_412' 'PATIENT_413' 'PATIENT_414' 'PATIENT_417' 'PATIENT_419'
 'PATIENT_421' 'PATIENT_423' 'PATIENT_424']
238

### Collating entire data

In [34]:
Patient_cohort_table = pd.DataFrame({'Pat_ID':patient_cohort1_list})
Patient_cohort_table['NSCLC Patients'] = Patient_cohort_table['Pat_ID'].isin(patient_cohort2_list)
Patient_cohort_table['mNSCLC Patients'] = Patient_cohort_table['Pat_ID'].isin(patient_cohort3_list)
Patient_cohort_table['mNSCLC_egfr Patients'] = Patient_cohort_table['Pat_ID'].isin(patient_cohort4_list)
Patient_cohort_table['mNSCLC_egfr_MKT Patients'] = Patient_cohort_table['Pat_ID'].isin(patient_cohort5_list)
Patient_cohort_table['mNSCLC_egfr_Ticaprant Patients'] =Patient_cohort_table['Pat_ID'].isin(patient_cohort6_list)
Patient_cohort_table['Chemo Patients'] = Patient_cohort_table['Pat_ID'].isin(unique_chemo_patient)
Patient_cohort_table.set_index('Pat_ID',inplace = True)

In [35]:
Patient_cohort_table.head()

,NSCLC Patients,mNSCLC Patients,mNSCLC_egfr Patients,mNSCLC_egfr_MKT Patients,mNSCLC_egfr_Ticaprant Patients,Chemo Patients
Pat_ID,,,,,,
PATIENT_001,True,True,True,True,True,False
PATIENT_002,True,True,True,True,False,False
PATIENT_003,True,True,True,True,True,False
PATIENT_004,True,True,True,True,False,False
PATIENT_005,True,True,True,True,False,False

#### Changing boolean flag to binary

In [36]:
Patient_cohort_table = Patient_cohort_table[Patient_cohort_table.columns].fillna(0).astype('int')
Patient_cohort_table.reset_index(inplace = True)

#### Merge both the dates table with the created cohort table

In [37]:
# Merge Both the table
Patient_cohort_table = Patient_cohort_table.merge(temp, on = 'Pat_ID', how = 'left')
Patient_cohort_table.set_index('Pat_ID',inplace = True)

In [38]:
Patient_cohort_table.head()

,NSCLC Patients,mNSCLC Patients,mNSCLC_egfr Patients,mNSCLC_egfr_MKT Patients,mNSCLC_egfr_Ticaprant Patients,Chemo Patients,first_NSCLC_diagnosis_date,first_mNSCLC_diagnosis_date,first_egfr_date,last_egfr_date
Pat_ID,,,,,,,,,,
PATIENT_001,1,1,1,1,1,0,20211229,20211229,20211229,20221122
PATIENT_002,1,1,1,1,0,0,20220102,20220102,20220102,20230112
PATIENT_003,1,1,1,1,1,0,20220331,20220331,20220331,20221228
PATIENT_004,1,1,1,1,0,0,20220310,20220310,20220310,20221125
PATIENT_005,1,1,1,1,0,0,20211224,20211224,20211224,20221219

#### Patient Cohort Summary

In [39]:
Patient_cohort = Patient_cohort_table[['NSCLC Patients','mNSCLC Patients','mNSCLC_egfr Patients','mNSCLC_egfr_MKT Patients','mNSCLC_egfr_Ticaprant Patients']]

In [40]:
pat_summary = Patient_cohort.sum(axis=0)

pat_summary_df = pd.DataFrame(pat_summary).transpose()

In [41]:
pat_summary_df

,NSCLC Patients,mNSCLC Patients,mNSCLC_egfr Patients,mNSCLC_egfr_MKT Patients,mNSCLC_egfr_Ticaprant Patients
0,423,348,180,150,72

#### Saving the Patient Cohort Analysis Data into a CSV file

In [42]:
Patient_cohort_table.to_csv('Synthetic Patient_cohort_table_final.csv')

# HCP Universe Analysis

#### Full Claims Data (Assuming Universe 1)

In [44]:
# Full claims data
HCP_universe1_data = mapped_df
HCP_universe1_list = mapped_df['HCP_ID'].unique()
HCP_universe1_count = mapped_df['HCP_ID'].nunique()
print(HCP_universe1_list)
print(HCP_universe1_count)

['HCP_17' 'HCP_01' 'HCP_28' 'HCP_16' 'HCP_21' 'HCP_09' 'HCP_33' 'HCP_29'
 'HCP_34' 'HCP_02' 'HCP_06' 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25'
 'HCP_10' 'HCP_19' 'HCP_24' 'HCP_03' 'HCP_30' 'HCP_18' 'HCP_31' 'HCP_13'
 'HCP_23' 'HCP_08' 'HCP_07' 'HCP_04' 'HCP_15' 'HCP_12' 'HCP_26' 'HCP_27'
 'HCP_32' 'HCP_62' 'HCP_39' 'HCP_58' 'HCP_64' 'HCP_55' 'HCP_35' 'HCP_78'
 'HCP_38' 'HCP_93' 'HCP_60' 'HCP_41' 'HCP_88' 'HCP_53' 'HCP_77' 'HCP_56'
 'HCP_65' 'HCP_44' 'HCP_72' 'HCP_80' 'HCP_87' 'HCP_57' 'HCP_59' 'HCP_49'
 'HCP_68' 'HCP_79' 'HCP_36' 'HCP_91' 'HCP_86' 'HCP_50' 'HCP_81' 'HCP_84'
 'HCP_66' 'HCP_45' 'HCP_42' 'HCP_37' 'HCP_52' 'HCP_71' 'HCP_76' 'HCP_46'
 'HCP_90' 'HCP_61' 'HCP_85' 'HCP_75' 'HCP_89' 'HCP_48' 'HCP_47' 'HCP_67'
 'HCP_82' 'HCP_73' 'HCP_92' 'HCP_40' 'HCP_70' 'HCP_74' 'HCP_83' 'HCP_69'
 'HCP_63' 'HCP_51' 'HCP_43']
91

#### HCPs treating NSCLC Patients (Universe 2)

In [45]:
# NSCLC HCPs
NSCLC_pat_list = patient_cohort2_list # Reference to Patient Cohort Analysis (Cohort 2)

HCP_universe2_data = HCP_universe1_data[HCP_universe1_data['Pat_ID'].isin(NSCLC_pat_list)]
HCP_universe2_list = HCP_universe2_data['HCP_ID'].unique()
HCP_universe2_count = HCP_universe2_data['HCP_ID'].nunique()
print(HCP_universe2_list)
print(HCP_universe2_count)

['HCP_17' 'HCP_01' 'HCP_28' 'HCP_16' 'HCP_21' 'HCP_09' 'HCP_33' 'HCP_29'
 'HCP_34' 'HCP_02' 'HCP_06' 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25'
 'HCP_10' 'HCP_19' 'HCP_24' 'HCP_03' 'HCP_30' 'HCP_18' 'HCP_31' 'HCP_13'
 'HCP_23' 'HCP_08' 'HCP_07' 'HCP_04' 'HCP_15' 'HCP_12' 'HCP_26' 'HCP_27'
 'HCP_32' 'HCP_62' 'HCP_39' 'HCP_58' 'HCP_64' 'HCP_55' 'HCP_35' 'HCP_78'
 'HCP_38' 'HCP_93' 'HCP_60' 'HCP_41' 'HCP_88' 'HCP_53' 'HCP_77' 'HCP_56'
 'HCP_65' 'HCP_44' 'HCP_72' 'HCP_80' 'HCP_87' 'HCP_57' 'HCP_59' 'HCP_49'
 'HCP_68' 'HCP_79' 'HCP_36' 'HCP_91' 'HCP_86' 'HCP_50' 'HCP_81' 'HCP_84'
 'HCP_66' 'HCP_45' 'HCP_42' 'HCP_37' 'HCP_52' 'HCP_71' 'HCP_76' 'HCP_46'
 'HCP_90' 'HCP_61' 'HCP_85' 'HCP_75' 'HCP_89' 'HCP_48' 'HCP_47' 'HCP_67'
 'HCP_82' 'HCP_73' 'HCP_92' 'HCP_40' 'HCP_70' 'HCP_74' 'HCP_83' 'HCP_69'
 'HCP_63' 'HCP_51' 'HCP_43']
91

#### HCPs treating mNSCLC Patients (Universe 3)

In [46]:
# mNSCLC HCPs
mNSCLC_pat_list = patient_cohort3_list # Reference to Patient Cohort Analysis (Cohort 3)

HCP_universe3_data = HCP_universe2_data[HCP_universe2_data['Pat_ID'].isin(mNSCLC_pat_list)]

HCP_universe3_list = HCP_universe3_data['HCP_ID'].unique()
HCP_universe3_count = HCP_universe3_data['HCP_ID'].nunique()
print(HCP_universe3_list)
print(HCP_universe3_count)

['HCP_17' 'HCP_01' 'HCP_28' 'HCP_16' 'HCP_21' 'HCP_09' 'HCP_33' 'HCP_29'
 'HCP_34' 'HCP_02' 'HCP_06' 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25'
 'HCP_10' 'HCP_19' 'HCP_24' 'HCP_03' 'HCP_30' 'HCP_18' 'HCP_31' 'HCP_13'
 'HCP_23' 'HCP_08' 'HCP_26' 'HCP_27' 'HCP_32' 'HCP_62' 'HCP_39' 'HCP_58'
 'HCP_64' 'HCP_55' 'HCP_78' 'HCP_93' 'HCP_41' 'HCP_88' 'HCP_53' 'HCP_77'
 'HCP_65' 'HCP_44' 'HCP_72' 'HCP_80' 'HCP_87' 'HCP_57' 'HCP_59' 'HCP_49'
 'HCP_68' 'HCP_79' 'HCP_36' 'HCP_91' 'HCP_86' 'HCP_50' 'HCP_35' 'HCP_81'
 'HCP_84' 'HCP_66' 'HCP_38' 'HCP_60' 'HCP_42' 'HCP_37' 'HCP_52' 'HCP_71'
 'HCP_76' 'HCP_46' 'HCP_90' 'HCP_61' 'HCP_75' 'HCP_56' 'HCP_48' 'HCP_47'
 'HCP_67' 'HCP_85' 'HCP_82' 'HCP_73' 'HCP_92' 'HCP_40' 'HCP_45' 'HCP_70'
 'HCP_83' 'HCP_63' 'HCP_89' 'HCP_51' 'HCP_74' 'HCP_43' 'HCP_69']
87

#### HCPs treating mNSCLC egfr patients (Universe 4)â€‹

In [47]:
# EGFR HCPs
egfr_pat_list = patient_cohort4_list # Reference to Patient Cohort Analysis (Cohort 4)

HCP_universe4_data = HCP_universe3_data[HCP_universe3_data['Pat_ID'].isin(egfr_pat_list)]
HCP_universe4_list = HCP_universe4_data['HCP_ID'].unique()
HCP_universe4_count = HCP_universe4_data['HCP_ID'].nunique()
print(HCP_universe4_list)
print(HCP_universe4_count)

['HCP_17' 'HCP_01' 'HCP_28' 'HCP_16' 'HCP_21' 'HCP_09' 'HCP_33' 'HCP_29'
 'HCP_34' 'HCP_02' 'HCP_06' 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25'
 'HCP_10' 'HCP_19' 'HCP_24' 'HCP_26' 'HCP_27' 'HCP_32' 'HCP_39' 'HCP_53'
 'HCP_77' 'HCP_44' 'HCP_72' 'HCP_80' 'HCP_87' 'HCP_62' 'HCP_49' 'HCP_68'
 'HCP_36' 'HCP_91' 'HCP_50' 'HCP_81' 'HCP_84' 'HCP_66' 'HCP_38' 'HCP_42'
 'HCP_71' 'HCP_78' 'HCP_76' 'HCP_86' 'HCP_41' 'HCP_46' 'HCP_48' 'HCP_82'
 'HCP_61' 'HCP_40' 'HCP_58' 'HCP_45' 'HCP_57' 'HCP_90' 'HCP_79' 'HCP_83'
 'HCP_59' 'HCP_52' 'HCP_85' 'HCP_89' 'HCP_74' 'HCP_43' 'HCP_60' 'HCP_93'
 'HCP_37' 'HCP_65' 'HCP_47' 'HCP_51' 'HCP_64' 'HCP_70' 'HCP_55' 'HCP_63'
 'HCP_69']
73

#### HCPs treating mNSCLC egfr patients with Market products patients (Universe 5)

In [48]:
# HCP treating with Market Product
mkt_prod_pat_list = patient_cohort5_list # Reference to Patient Cohort Analysis (Cohort 5)

HCP_universe5_data = HCP_universe4_data[HCP_universe4_data['Pat_ID'].isin(mkt_prod_pat_list)]
HCP_universe5_list = HCP_universe5_data['HCP_ID'].unique()
HCP_universe5_count = HCP_universe5_data['HCP_ID'].nunique()
print(HCP_universe5_list)
print(HCP_universe5_count)

['HCP_17' 'HCP_01' 'HCP_28' 'HCP_16' 'HCP_21' 'HCP_09' 'HCP_33' 'HCP_29'
 'HCP_34' 'HCP_02' 'HCP_06' 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25'
 'HCP_26' 'HCP_27' 'HCP_32' 'HCP_39' 'HCP_53' 'HCP_77' 'HCP_44' 'HCP_72'
 'HCP_80' 'HCP_87' 'HCP_62' 'HCP_49' 'HCP_68' 'HCP_36' 'HCP_91' 'HCP_50'
 'HCP_81' 'HCP_84' 'HCP_66' 'HCP_71' 'HCP_78' 'HCP_76' 'HCP_86' 'HCP_41'
 'HCP_46' 'HCP_82' 'HCP_61' 'HCP_58' 'HCP_45' 'HCP_57' 'HCP_90' 'HCP_79'
 'HCP_83' 'HCP_52' 'HCP_85' 'HCP_48' 'HCP_74' 'HCP_43' 'HCP_60' 'HCP_93'
 'HCP_37' 'HCP_59' 'HCP_42' 'HCP_65' 'HCP_51' 'HCP_64' 'HCP_70' 'HCP_55'
 'HCP_63' 'HCP_69' 'HCP_40']
67

#### HCPs treating mNSCLC egfr patients with Ticaprant (Universe 6)

In [49]:
# Ticaprant HCPs
ticaprant_pat_list = patient_cohort6_list # Reference to Patient Cohort Analysis (Cohort 6)

HCP_universe6_data = HCP_universe5_data[HCP_universe5_data['Pat_ID'].isin(ticaprant_pat_list)]
HCP_universe6_list = HCP_universe6_data['HCP_ID'].unique()
HCP_universe6_count = HCP_universe6_data['HCP_ID'].nunique()
print(HCP_universe6_list)
print(HCP_universe6_count)

['HCP_17' 'HCP_28' 'HCP_09' 'HCP_33' 'HCP_29' 'HCP_34' 'HCP_02' 'HCP_06'
 'HCP_05' 'HCP_11' 'HCP_22' 'HCP_20' 'HCP_25' 'HCP_39' 'HCP_53' 'HCP_72'
 'HCP_62' 'HCP_49' 'HCP_91' 'HCP_66' 'HCP_78' 'HCP_76' 'HCP_86' 'HCP_82'
 'HCP_61' 'HCP_87' 'HCP_58' 'HCP_90' 'HCP_52' 'HCP_50' 'HCP_36' 'HCP_48'
 'HCP_84' 'HCP_60' 'HCP_93' 'HCP_59' 'HCP_68' 'HCP_65' 'HCP_64' 'HCP_37'
 'HCP_79' 'HCP_40']
42

### Collating Data

In [50]:
HCP_universe_table = pd.DataFrame({'HCP_ID':HCP_universe1_list})
HCP_universe_table['NSCLC HCP'] = HCP_universe_table['HCP_ID'].isin(HCP_universe2_list)
HCP_universe_table['mNSCLC HCP'] = HCP_universe_table['HCP_ID'].isin(HCP_universe3_list)
HCP_universe_table['mNSCLC_egfr HCP'] =HCP_universe_table['HCP_ID'].isin(HCP_universe4_list)
HCP_universe_table['mNSCLC_egfr_MKT HCP'] = HCP_universe_table['HCP_ID'].isin(HCP_universe5_list)
HCP_universe_table['mNSCLC_egfr_Ticaprant HCP'] = HCP_universe_table['HCP_ID'].isin(HCP_universe6_list)
HCP_universe_table.set_index('HCP_ID',inplace = True)

In [51]:
HCP_universe_table.head()

,NSCLC HCP,mNSCLC HCP,mNSCLC_egfr HCP,mNSCLC_egfr_MKT HCP,mNSCLC_egfr_Ticaprant HCP
HCP_ID,,,,,
HCP_17,True,True,True,True,True
HCP_01,True,True,True,True,False
HCP_28,True,True,True,True,True
HCP_16,True,True,True,True,False
HCP_21,True,True,True,True,False

In [52]:
HCP_universe_table = HCP_universe_table[HCP_universe_table.columns].fillna(0).astype('int')

In [53]:
HCP_summary = HCP_universe_table.sum(axis = 0)

HCP_summary_df = pd.DataFrame(HCP_summary).transpose()

In [54]:
HCP_summary_df

,NSCLC HCP,mNSCLC HCP,mNSCLC_egfr HCP,mNSCLC_egfr_MKT HCP,mNSCLC_egfr_Ticaprant HCP
0,91,87,73,67,42

#### Saving the HCP Universe Table into CSV file

In [55]:
HCP_universe_table.to_csv('Synthetic HCP_universe_table_final.csv')